FROM golang:1.26.5-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY services/api-gateway/go.mod services/api-gateway/go.sum ./

RUN go mod download

COPY services/api-gateway .

EXPOSE 8000

CMD ["air", "-c", ".air.toml"]
