FROM golang:1.26.7-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY services/profile/go.mod services/profile/go.sum ./

RUN go mod download

COPY services/profile .

EXPOSE 4000

CMD ["air", "-c", ".air.toml"]
