FROM golang:1.26.7-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY services/current-user/go.mod services/current-user/go.sum ./

RUN go mod download

COPY services/current-user .

EXPOSE 4000

CMD ["air", "-c", ".air.toml"]
